baseurl: https://algo.ulb.be/
title: Algorithms Research Group (ULB)
theme: hugo-creative-portfolio-theme
languageCode: en-us
# Enable comments by entering your Disqus shortname
#disqusShortname:
# Enable Google Analytics by entering your tracking code
#googleAnalytics:

sitemap:
  changefreq: monthly
  priority: 1

params:
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style: blue
  description: Website for the algo group @ ULB.
  #copyright:
  mobileNavAbout: >
    <b><a href="http://algo.ulb.be">Algorithms Research Group</a></b><br>
    <a href="http://www.ulb.ac.be/facs/sciences/info/index-en.html">Computer Science Department</a><br>
    <a href="http://www.ulb.ac.be/facs/sciences">Faculté des Sciences</a><br>
    <a href="http://www.ulb.ac.be">Université libre de Bruxelles (ULB)</a><br>
    Campus de la Plaine, CP 212<br>
    B-1050 Brussels, Belgium<br>
  sidebarAbout:
    - >
      <b><a href="http://algo.ulb.be">Algorithms Research Group</a></b><br>
      <a href="http://www.ulb.ac.be/facs/sciences/info/index-en.html">Computer Science Department</a><br>
      <a href="http://www.ulb.ac.be/facs/sciences">Faculté des Sciences</a><br>
      <a href="http://www.ulb.ac.be">Université libre de Bruxelles (ULB)</a><br>
      Campus de la Plaine, CP 212<br>
      B-1050 Brussels, Belgium<br>
    - >
        <img src="/img/delaunay.png" alt="" class="img-responsive">
    - >
      Keywords: Discrete and computational geometry,
      algorithmic and structural graph theory,
      combinatorial optimization, data structures.
    #- >
      #Currently funded research projects:
      #EUROCORES EuroGIGA <a href="http://eurogiga-compose.eu/about.php">ComPoSe</a> and
      #<a href="http://eurogiga.inf.fu-berlin.de/w/VORONOI/">VORONOI</a>,
      #and ARC <a href="http://www.ulb.ac.be/recherche/presentation/fr-arccerf.html">COPHYMA</a>.

  # Contact page
  # Since this template is static, the contact form uses www.formspree.io as a
  # proxy. The form makes a POST request to their servers to send the actual
  # email. Visitors can send up to a 1000 emails each month for free.
  #
  # What you need to do for the setup?
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email yourself to confirm your account
  # - click the confirm link in the email from www.formspree.io
  # - you're done. Happy mailing!
  #email:

  navlinks:
    # Nav links in the side bar
    - name: "The team"
      url: ""

    - name: "Alumni"
      url: "alumni/"

    - name: "Visitors"
      url: "visitors/"

  extlinks:
    # External nav links in the side bar
    - name: "Algo Lunch"
      url: "http://www.ulb.ac.be/di/algo/gjoret/algolunch.html"

  #social:
    #facebook:
    #googleplus:
    #email:
    #twitter:
    #linkedin:
    #stackoverflow:
    #instagram:
    #github:

  team:

    # Permanent staff

    - name: Jean Cardinal
      image: https://ipfs.io/ipfs/QmQ34i4KTp5nJzGc6TKS2pBRpr626BXwgsqzVeJ1ASBDYA
      webpage: http://homepages.ulb.ac.be/~jcardin
      description: Professor
      keywords: Discrete and computational geometry, graphs, information theory.
      office: 2.O8.112
      phone: 02/650.5608
      email: jcardin@ulb.ac.be

    - name: Samuel Fiorini
      image: https://ipfs.io/ipfs/QmVorega83U1rsez2K1vzfWKNbWkPhak73SyxCjUfCuuKD
      webpage: http://homepages.ulb.ac.be/~sfiorini
      description: Professor (Math Department)
      keywords: Combinatorial optimization, polyhedral combinatorics, graph theory.
      email: sfiorini@ulb.ac.be

    - name: Gwenaël Joret
      image: https://ipfs.io/ipfs/QmazTYo9aGewcVAqz4P9ksxBUTd5nR9fNNGy7Bt1ZD4BGL
      webpage: http://www.ulb.ac.be/di/algo/gjoret
      description: Assistant Professor
      keywords: Graph theory, combinatorial optimization, approximation algorithms.
      office: 2.O8.111
      phone: 02/650.5759
      email: gjoret@ulb.ac.be

    - name: Stefan Langerman
      image: https://ipfs.io/ipfs/QmUFVyZJx8rLmPVg3dZVxAHxhwojSynSgCauWMYNUBZFCt
      webpage: https://algo.ulb.be/sl
      description: Directeur de recherches (FNRS Research Director)
      keywords: Computational geometry, data structures.
      office: 2.O8.113
      phone: 02/650.5928
      email: stefan.langerman@ulb.ac.be

    - name: John Iacono
      image: https://ipfs.io/ipfs/Qma1hSDADUUPpLXmz5qV7yJiUEBC4QW9DvZsnmVCyqe1wy
      webpage: http://johniacono.com
      description: Professor
      keywords: Data structures, computational geometry.
      office: 2.O8.114
      email: ulb@johniacono.com

    - name: Guy Louchard
      image: https://ipfs.io/ipfs/QmTxwi3ypGMAFKWMvS5Sa5fYbHvjHAw6gKZhNSYcQbsVSZ
      webpage: http://www.ulb.ac.be/di/mcs/louchard
      description: I am now retired so I can devote (almost) all my time to research.
      keywords: Probabilistic techniques
      office: 2.N8.206
      phone: 02/650.5613
      email: louchard@ulb.ac.be

    # Postdocs

    - name: Suman Bala
      description: Postdoc (Algo & QualSec)
      image: https://ipfs.io/ipfs/QmWsje7GrgLPsr6dYZwQysudLnWK85Srpj7FZCKBruE6FM
      email: suman1005@gmail.com

    - name: Wouter Cames van Batenburg
      image: https://ipfs.io/ipfs/QmZmg8woxSuzCrXLdR15ofLxHFP8MW8CKDRmXPcfD1TJtX
      webpage: http://homepages.ulb.ac.be/~wcamesva/
      description: Postdoc
      keywords: extremal combinatorics, percolation, colouring and packing of graphs.
      office: 2.O8.110

    - name: Grigorios Koumoutsos
      description: Postdoc
      image: https://ipfs.io/ipfs/QmU3R3HAQ1tgkMx5ndR3pVoWtrJQJaCRxfedBABPkSxbcY
      webpage: http://homepages.ulb.ac.be/~gkoumout/
      keywords: Online Algorithms, Online Learning, Data Structures
      office: 2.O8.214
      email: gkoumout@ulb.ac.be
      
      
    - name: Ben Karsin
      description: Postdoc
      image: https://ipfs.io/ipfs/QmSEW67JtHEmGE8Gyx4SQycrHycLK7a6PYSw5G5rvSDvmw
      webpage: https://benkarsin.com
      office: 2.O8.214

    - name: Tony Huynh
      description: Postdoc (Math Department)
      image: https://ipfs.io/ipfs/QmTQZQBG5QMM51Fpo6VQMNBaWGsBqZPkwGQHSzhsCjTT7f
      webpage: https://sites.google.com/site/matroidintersection

    - name: Krystal Guo
      description: Postdoc (Math Department)
      image: https://ipfs.io/ipfs/QmaQAqMjeSL8MG8NGDvTCCiWWxns8vcKGiKaqpQDfnkUd3
      webpage: https://simons.berkeley.edu/people/krystal-guo

    - name: Marco Macchia
      description: Postdoc. Former PhD student (Math Department).
      image: https://ipfs.io/ipfs/QmfUPALGifDH4kkVoH7NjDrXpPkfSkJ7yU3Quuxzqjigbn
      webpage: http://homepages.ulb.ac.be/~mmacchia

    - name: Yann Barsamian
      description: Postdoc
      image: https://ipfs.io/ipfs/QmXaVLsMCTQhjwUVRjnFz8qvXk5PSocHJxjeCCf13gntbE
      webpage: https://barsamian.am

    - name: Seungbum Jo
      description: Future Postdoc
      image: https://ipfs.io/ipfs/QmPCn2FVCYLWp4XQ8xaWGKQ6bxAk6MgJKreSknrUS6BSkz


    # PhD students

    - name: Keno Merckx
      image: https://ipfs.io/ipfs/QmfC5XE7pPTPfrUy6FywZVHxgnNAF5rBDyYC99dgiEkR34
      webpage: http://homepages.ulb.ac.be/~kmerckx
      description: PhD student
      keywords: Graphs
      email: kmerckx@ulb.ac.be

    - name: Aurélien Ooms
      description: PhD student
      image: https://ipfs.io/ipfs/Qmd7fiq1Sq9G5b9hd5inHU3GZhPCm424xyKbCeFjGEtFQd
      webpage: http://homepages.ulb.ac.be/~aureooms
      keywords: "Computational Complexity: Data Structures, Algorithms, Computational Geometry."
      office: 2.O8.214
      email: aureooms@ulb.ac.be

    - name: Carole Muller
      description: PhD student (Math Department)
      image: https://ipfs.io/ipfs/QmWQ3vjAjXHTQfRUD77uFSAnjEjjat2vGVENoUhADKjcPE
      webpage: http://student.ulb.ac.be/~camuller

    - name: Matthew Drescher
      description: PhD student (Math Department)
      image: https://ipfs.io/ipfs/QmfP581LiyDm7EEZgBzFCxG5sCuyQuEdjtmgXp1hjDWSMu


    # External members

    - name: Sébastien Collette
      image: https://ipfs.io/ipfs/QmXhj22o8Voizc5QEXBJNp4944DXaLAUqMWhFgFL87LbkD
      webpage: http://www.ulb.ac.be/di/algo/secollet
      description: Visiting professor (Maître de Conférence) at ULB. Consultant at Synapsis.
      keywords: Computational geometry, data structures.
      email: sebastien.collette@ulb.ac.be


  alumni:

    - name: Varunkumar Jayapaul
      description: Former Postdoc
      image: https://ipfs.io/ipfs/QmSrFZ2AP9dX9G2QyCVmRUNCoz4eNu1QPQdWDVMBSjyRQt
      email: varunkumarj@gmail.com

    - name: Tillmann Miltzow
      image: https://ipfs.io/ipfs/QmQURgrZnSW9e5zxo7rofTbifj472a7iwTmqapjzxaTRYf
      webpage: http://sites.google.com/view/miltzow/home
      description: Former Postdoc (Algo group and Math Department). Researcher at [Utrecht University](https://www.uu.nl/en).
      keywords: Computational geometry.
      email: t.miltzow@googlemail.com

    - name: Elena Arseneva (Khramtcova)
      image: https://ipfs.io/ipfs/QmfZ3TCc6JVpQL4D9CEVbdZCudpfN9RHML6AmenxpmUMoi
      webpage: http://homepages.ulb.ac.be/~ekhramtc
      description: >
        Assistant Professor (старший преподаватель) in the Mathematics and TCS
        Program of [St. Petersburg State University](http://english.spbu.ru),
        Russia.
        Former Postdoc.
      keywords: Computational Geometry, Algorithms, Data Structures, Voronoi diagrams.
      email: elena.khramtsova@gmail.com

    - name: Udo Hoffmann
      image: https://ipfs.io/ipfs/QmVD2V1tt3HiY8C3v6NwJnzPWkdH8tdrT4LkPHzws5TCDm
      webpage: https://udohoffmann.bitbucket.io
      description: Former Postdoc
      keywords: Combinatorial geometry.
      email: udo.hoffmann@ulb.ac.be

    - name: Irina Kostitsyna
      image: https://ipfs.io/ipfs/QmQvBdfpPufgKGCY9X71KEqpkK7mZnEExohqbgH3Z53tGG
      webpage: http://homepages.ulb.ac.be/~ikostits
      description: >
        Assistant professor in the Applied Geometric Algorithms
        group at the Department of Mathematics and Computer Science at
        [TU Eindhoven](https://www.tue.nl/en). Former Postdoc.
      keywords: "Computational Geometry: Polygons."
      email: irina.kostitsyna@ulb.ac.be

    - name: Andrew Winslow
      description: Software engineer at Google. Former Postdoc.
      webpage: http://andrewwinslow.com
      email: andrew.winslow+ulb@gmail.com
      image: https://ipfs.io/ipfs/QmWR2L3c7cZ5dewpPTBJJzb89mxgiMZUqiSbzyQxAnkfm6
      keywords: Algorithmic self-assembly, computational geometry

    - name: Luis Barba
      description: >
        Postdoc at [ETH Zürich](https://www.ethz.ch/en.html), Switzerland,
        working in the group of [Professor Emo
        Welzl](https://www.inf.ethz.ch/personal/emo).
        Former PhD student.
      webpage: http://cglab.ca/~lfbarba
      email: luis.barba@inf.ethz.ch
      image: https://ipfs.io/ipfs/QmNrnrCXKNX8eQeCQ3wqX1T7JiPQooVWecBjkTUrR9B8EW

    - name: Vissarion Fisikopoulos
      description: >
        Senior software engineer at [Oracle](https://www.oracle.com), working on development of
        geometric algorithms for GIS in
        [Boost.Geometry](http://www.boost.org/doc/libs/1_62_0/libs/geometry/doc/html/index.html)
        to support [MySQL](https://www.mysql.com). Former Postdoc.
      image: https://ipfs.io/ipfs/QmbJbuySR2bps8jz6VdSQb9Y2pjAidfbkP2GqX6Dcumgmz
      webpage: https://vissarion.github.io
      keywords: Discrete geometry, polyhedral combinatorics
      email: vissarion.fysikopoulos@oracle.com

    - name: Eglantine Camby
      description: >
        Junior researcher as a postdoc from the
        [Computer Science Department](http://www.ulb.ac.be/facs/sciences/info)
        at the [Université libre de
        Bruxelles (ULB)](http://www.ulb.ac.be) in Belgium, under the supervision
        of [Martine Labbé](http://homepages.ulb.ac.be/~mlabbe).
        Currently, one-year visitor in [HEC
        Montréal](http://www.hec.ca) and [GERAD](https://www.gerad.ca/fr), in Canada,
        under the supervision of
        [Gilles Caporossi](http://www.hec.ca/profs/gilles.caporossi.html).
        Former PhD student.
      webpage: http://homepages.ulb.ac.be/~ecamby
      email: Eglantine.Camby@ulb.ac.be
      image: https://ipfs.io/ipfs/QmUuiSdoEP7h2jQsB2ri98LecTEeUQBtVfeWKQ349SueSo

    - name: Michael Payne
      description: Lecturer, [La Trobe University](https://www.latrobe.edu.au). Former Postdoc.
      webpage: http://www.ms.unimelb.edu.au/~mspayne
      email: mpayne@ulb.ac.be
      keywords: Discrete geometry, geometric graph theory.
      image: https://ipfs.io/ipfs/QmRXmtEWxpZwedLV5Hgwocz5FzBfgYd1wsbbm4syoTjubS

    - name: Greg Aloupis
      description: >
        Industry Professor, [New York University](https://www.nyu.edu).
        Former Chargé de recherches du FNRS (FNRS Postdoctoral Researcher).
      keywords:  Computational geometry
      email: aloupis.greg@gmail.com
      image: https://ipfs.io/ipfs/QmaJ5xL5ayuAidGnYJ8C79SxEZ31uXmcbuPG8vuF1xkQxi
      webpage: http://cg.scs.carleton.ca/~greg

    - name: Matias Korman
      description: Visiting Assistant Professor at [Tufts](https://www.tufts.edu). Former Postdoc.
      keywords: >
        Geometric shortest path planning,
        Memory constrained algorithms,
        Battery management in ad-hoc networks.
      email: Matias.Korman@tufts.edu
      image: https://ipfs.io/ipfs/QmXCywhBwRszxqteZDhYcAuJymvNhB1VUqaBaJEUpqrk2g
      webpage: https://engineering.tufts.edu/people/faculty/matias-korman

    - name: Marcin Kaminski
      description: Chargé de recherches du FNRS (FNRS Postdoctoral Researcher).
      keywords: Graph theory, Algorithms.
      email: Marcin.Kaminski@ulb.ac.be
      image: https://ipfs.io/ipfs/Qme5HJA6k5hQXkzwpoh4RRXyLoi3jLTLDt2LoHBNxowDDH
      webpage: http://rutcor.rutgers.edu/~mkaminski

    - name: Pegah Kamousi
      keywords: Probabilistic Optimization, Computational Geometry
      email: pegahk@gmail.com
      image: https://ipfs.io/ipfs/QmQ6GNdTTXKP33svqpEXneHPvN9a3bQpUwrFeBf4ZaBZWX
      description: Former Postdoc

    - name: Maria Saumell
      keywords: Computational Geometry
      email: maria.saumell.m@gmail.com
      image: https://ipfs.io/ipfs/QmWsbhrnqqeib4vd9BG1nzdtPx3AXJHq9XwcxUy1Dqxg5u
      webpage: http://home.zcu.cz/~saumell

    - name: Luca Castelli-Aleardi
      image: https://ipfs.io/ipfs/QmT6xPNSnM7BPLzGApGUiFeAeSzG6Tr43DwX8VrGvXmN7S
      webpage: http://www.lix.polytechnique.fr/~amturing

    - name: Nathann Cohen
      image: https://ipfs.io/ipfs/QmTESbccAAmoMQSW4faEK9YnhaUGhTVHLY7cVjzccJ4Zvt
      webpage: http://steinertriples.fr/ncohen

    - name: Raphael Jungers
      image: https://ipfs.io/ipfs/QmdPaZajPa7PJFmsH7j6QaDMLGXZtMgkLAPL3FtcMeFAFr
      webpage: http://perso.uclouvain.be/raphael.jungers

    - name: Perouz Taslakian
      image: https://ipfs.io/ipfs/Qma2Mo3y5C8CRHsXjhL73BQ3mcfUaTcTVwHeAFCh4CSLou
      webpage: http://homepages.ulb.ac.be/~ptaslaki

    - name: Karim Douïeb
      image: https://ipfs.io/ipfs/QmcMmYXaKMSBDbgmDvTUdwDqCMGZjqQegCWypGrms8RMyM
      webpage: http://www.ulb.ac.be/di/algo/kdouieb
      description: Co-Founder - [Jetpack.AI](https://jetpack.ai). Former PhD student.


  visitors:

    - name: Sergio Cabello
      image: https://ipfs.io/ipfs/QmUv8qbTbkmjzMCjzNszTpZLzYqyE65bno8DQTsiru9Px5
      visiting: January 2019
      webpage: https://www.fmf.uni-lj.si/~cabello

    - name: Maarten Löffler
      image: https://ipfs.io/ipfs/QmZbGWfHEBNfsGUK6NxrbcpBFtyy75MJ6eiVVV65rHVaLr
      visiting: November 2018
      webpage: https://www.staff.science.uu.nl/~loffl001/about.html

    - name: Lena Yuditsky
      image: https://ipfs.io/ipfs/QmVtzbnAP7moyyg2gze2E1AQ9s4Vm4AxZbb3WavRjEJh8K
      visiting: October 2018
      webpage: http://www.math.kit.edu/iag6/~yuditsky

    - name: Bartosz Walczak
      image: https://ipfs.io/ipfs/QmeqdVqDEzSKsic5qC1AZfHhQgsMJCJus81fUPsGcXUDet
      visiting: August 2018
      webpage: http://www.tcs.uj.edu.pl/walczak

    - name: Riko Jacob
      image: https://ipfs.io/ipfs/QmVAML1Axvr5fsSa266tYKYsB5kqnBp7PeHS8gryFnTn6J
      visiting: July 2018
      webpage: https://www.itu.dk/people/rikj

    - name: Konstantinos A. Tsakalidis
      image: https://ipfs.io/ipfs/QmPugFGipV3uNau4jQAwUwpqnJR33UhHVHibMTNgZVoggs
      visiting: July 2018
      webpage: http://www.madalgo.au.dk/~tsakalid

    - name: Nodari Sitchinava
      image: https://ipfs.io/ipfs/QmeSwWPWKbBZeh7JSaJ9ErGEfRA5HBZKyhh3tCtRH6oWas
      visiting: July 2018
      webpage: https://www2.hawaii.edu/~nodari

    - name: Torsten Ueckerdt
      image: https://ipfs.io/ipfs/QmfDBMyXKo6Vs3o4cLKfYc8VwsT5XBjXQx71vru88Q74jZ
      visiting: April 2018
      webpage: http://www.math.kit.edu/iag6/~ueckerdt/en

    - name: Kolja Knauer
      image: https://ipfs.io/ipfs/QmQZjzbJcdxRoGpTfTNbSxkPwQqXkCmKCkkHSRucJghEtn
      visiting: April 2018
      webpage: http://pageperso.lif.univ-mrs.fr/~kolja.knauer

    - name: Piotr Micek
      image: https://ipfs.io/ipfs/QmddzmK2Y6J7YrPaFWzo74HiDfJQpfT2Bc9kgQSotBoXNQ
      visiting: April 2018
      webpage: http://page.math.tu-berlin.de/~micek

    - name: Sander Gribling
      image: https://ipfs.io/ipfs/QmbCqo88Ui4KixgWQ7D4BmFXwPHWkQ8uFNFSeg5pAwcwJj
      visiting: April 2018
      webpage: https://www.cwi.nl/people/sander-gribling

    - name: Natalia Garcia Colin
      image: https://ipfs.io/ipfs/QmVS6ZxV4VfDcVDgkL1qb7vNqmgp5bhD7KCtDhBjAauyiY
      visiting: March - April 2018
      webpage: https://www.infotec.mx/es_mx/infotec/natalia_garcia_colin

    - name: Ahmad Abdi
      image: https://ipfs.io/ipfs/QmPcPWrrFBvzzxCpDM6MGqA7WrMx2pap2e5n3AqqxCnzWd
      visiting: March 2018
      webpage: https://www.math.uwaterloo.ca/~a3abdi

    - name: Mikkel Abrahamsen
      image: https://ipfs.io/ipfs/QmZdw7CEYoPJjeqih7bDooRmZ8arigpaHoKXdr1wSSiRFr
      visiting: February 2018
      webpage: http://diku.dk/english/staff/?pure=en/persons/289414

    - name: Grigorios Koumoutsos
      image: https://ipfs.io/ipfs/QmU3R3HAQ1tgkMx5ndR3pVoWtrJQJaCRxfedBABPkSxbcY
      visiting: February 2018
      webpage: https://www.win.tue.nl/~gkoumout

    - name: Thatchapol Saranurak
      image: https://ipfs.io/ipfs/QmTw7x8dqyT7AAJcZ4VbYn7FfFPxHzdGfjh63PKqbBNMJy
      visiting: January 2018
      webpage: https://sites.google.com/site/thsaranurak

    - name: Luis Barba
      image: https://ipfs.io/ipfs/QmNrnrCXKNX8eQeCQ3wqX1T7JiPQooVWecBjkTUrR9B8EW
      visiting: November 2017
      webpage: http://cglab.ca/~lfbarba

    - name: Wouter Cames van Batenburg
      image: https://ipfs.io/ipfs/QmZmg8woxSuzCrXLdR15ofLxHFP8MW8CKDRmXPcfD1TJtX
      visiting: November 2017
      webpage: https://www.math.ru.nl/~woutercvb
